### ISSUE TITLE
Error when instantiating Vibrate

### ISSUE THREAD

**Issue by dhabierre** [bazzite/nativescript-vibrate#11]
I"m following this documentation: https://nativescript-vibrate-docs.bazzite.com/

But when I add these lines:

> { Vibrate } from 'nativescript-vibrate';
> let Vibrator = new Vibrate(); // if I remove it, it is OK.

I get this exception when the app starts (without using the vibrate() method)):

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

TypeError: Cannot read property 'getSystemService' of undefined
File: "file:///data/data/com.ananapps.Crebits/files/app/tns_modules/nativescript-vibrate/vibrate.js, line: 9, column: 43

StackTrace: 
	Frame: function:'Vibrate', file:'file:///data/data/com.ananapps.Crebits/files/app/tns_modules/nativescript-vibrate/vibrate.js', line: 9, column: 44
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/pages/operation-list/operation-list.component.js', line: 16, column: 16
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/app.routing.js', line: 9, column: 34
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266

TypeError: Cannot read property 'getSystemService' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'Vibrate', file:'file:///data/data/com.ananapps.Crebits/files/app/tns_modules/nativescript-vibrate/vibrate.js', line: 9, column: 44
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/pages/operation-list/operation-list.component.js', line: 16, column: 16
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/app.routing.js', line: 9, column: 34
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/app.module.js', line: 5, column: 21
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/com.ananapps.Crebits/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266

Permission is set manually, the tns add cmd does not add it in the manifest.

Any idea?
Thanks!

**Comment by juliomrqz** [comment]
Hello @dhabierre.

I can't help you with the information you provided. Please, follow the instruction presented when creating a issue (https://raw.githubusercontent.com/bazzite/nativescript-vibrate/develop/.github/issue_template.md)

Thanks.

**Comment by OwenMelbz** [comment]
@dhabierre did you find a solution? i'm having the same problem only on android

**Comment by dhabierre** [comment]
No, sorry.

**Comment by Narkoleptika** [comment]
@OwenMelbz @dhabierre 

I was able to resolve this issue by instantiating `Vibrate` later on in the app lifecycle.

The issue is [here](https://github.com/bazzite/nativescript-vibrate/blob/develop/src/vibrate.android.ts#L8) in the source code.

Basically, if you call `new Vibrate()` too early, `app.android.context` will be undefined. 

I'm not sure when `app.android.context` gets defined, but you need to make sure you call `new Vibrate()` afterwards.
