### ISSUE TITLE
Permission exception with Nativescript 4.0 (Android)

### ISSUE THREAD

**Issue by erjdriver** [bazzite/nativescript-vibrate#15]
Getting an exception when using with NS 4.0, TNS 4.0 and Android 4.0.1

Using plug-in 2.0.2

Have used this plugin for a while - and first time getting exception.

I looked at the platforms/../AndroidManifest.xml file and the VIBRATE permission is not there.

![screenshot_20180429-163054](https://user-images.githubusercontent.com/1229041/39410772-5ddc3ba2-4bcb-11e8-8ebb-cd42690f788f.png)

**Comment by juliomrqz** [comment]
Hello @erjdriver. This plugin does not support NativeScript 4.0 yet. This week we will add support for latest version of NativeScript.

**Comment by erjdriver** [comment]
ok - good enough.

Thank you.

**Comment by juliomrqz** [comment]
@erjdriver A new version has been published.
