### ISSUE TITLE
Not working on iPhone X running iOS 12 (with potential solution)

### ISSUE THREAD

**Issue by EddyVerbruggen** [bazzite/nativescript-vibrate#18]
Hi,

This plugin works great on Android, but the only iOS device I've tested it on won't vibrate.

After searching the web the only way I could make it work was:

```
AudioServicesPlaySystemSoundWithCompletion(1352, null);

// or (the deprecated version)
AudioServicesPlaySystemSound(1352);
```

I know it's a bit of a magic number, but it seems to work for everyone facing this issue.

Happy to do a PR if you agree.

**Comment by juliomrqz** [comment]
Hello, Eddy. 

I agree with you. We'll happy if you do a PR.

Thank you.

**Comment by juliomrqz** [comment]
Hello, @EddyVerbruggen. Your fix is now integrated in the latest release [v2.1.2](https://github.com/bazzite/nativescript-vibrate/releases).

Thank you for your contribution 🤓.

**Comment by EddyVerbruggen** [comment]
Awesome, thanks @juliomrqz!
