### ISSUE TITLE
Android Pattern Vibration

### ISSUE THREAD

**Issue by iesrbt** [bazzite/nativescript-vibrate#3]
In case anyone needs it:

//==============

var app = require('application');
    
var vibrator = (function() {
var default_pattern = [0, 222, 111, 222, 111, 222, 111],
_pattern = Array.create('long', default_pattern.length);
default_pattern.forEach(function(elm, idx) { _pattern[idx]=elm });
var self = {
_vibrator_service: null,
_check: function() {
if(!self._vibrator_service)
self._vibrator_service = app.android.context.getSystemService(android.content.Context.VIBRATOR_SERVICE);    
},  
vibration: function(milliseconds) {
self._check();
if(self._vibrator_service.hasVibrator()) {
milliseconds = typeof milliseconds !== 'undefined' ? milliseconds : 333;
self._vibrator_service.vibrate(milliseconds);
}
},
pattern: function(pattern, repeat) {
self._check();
if(self._vibrator_service.hasVibrator()) {
if(pattern && pattern.length && (pattern.length & 1)) {
var longs = Array.create('long', pattern.length);
pattern.forEach(function(elm, idx) { longs[idx]=elm });
pattern = longs;
} else
pattern = _pattern;
repeat = typeof repeat !== 'undefined' ? repeat : -1;
self._vibrator_service.vibrate(pattern, repeat);
}
},
cancel: function() {
self._check();
self._vibrator_service.cancel();    
}
};
return self;
})();

module.exports = vibrator;

//==============

Usage:

//==============

vibrator.pattern();

vibrator.pattern([0,500,250,1000,250]);

vibrator.pattern([0,500,200], 0);
setTimeout(vibrator.cancel, 5555);

**Comment by juliomrqz** [comment]
Android Pattern Vibration is now supported in **develop**. Feel free to contribute, the package is now actively maintained.
