### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by juliomrqz** [bazzite/nativescript-vibrate#5]
Hello. My team and I would like to take onwership of this repository.

Thanks

**Comment by anarchicknight** [comment]
Thanks.

Do you want me to transfer it to your github username or do you have a different one you want it transferred to?

**Comment by juliomrqz** [comment]
Hi. I have a different one, this username [bazzite](https://github.com/bazzite/). Thanks.

**Comment by juliomrqz** [comment]
You can use the same username in npmjs.com.

**Comment by anarchicknight** [comment]
You are now added as owner on npm.

Trying to transfer ownership of repo here is giving me this message "You don’t have the permission to create repositories on bazzite"

**Comment by juliomrqz** [comment]
I see... Just add me as an admin to the project and I'll do the transfer. Thanks.

**Comment by anarchicknight** [comment]
I couldn't seem to add another admin so I have transferred it to your personal github - you should then be able to transfer it to the bazzite one

**Comment by juliomrqz** [comment]
Perfect. The transfer of the ownership is done.
