### ISSUE TITLE
.vibrate() or .Vibrate()?

### ISSUE THREAD

**Issue by Frustrated-Programmer** [bazzite/nativescript-vibrate#62]
So all the docs for this plugin that i found:
 - https://github.com/bazzite/nativescript-vibrate
 - https://www.npmjs.com/package/nativescript-vibrate
 - https://www.nsplugins.com/plugin/nativescript-vibrate
All use the code:
`vibrator.vibrate(2000);` **Lowercase V**
And when I used it, it threw an error saying `.vibrate() is not a function`
I then used `console.dir(vibrator)` and it returned a single function `.Vibrator()` with an **Uppercase V**

Just a heads up that something in the docs or the code is mistaken.

**Comment by juliomrqz** [comment]
Hi, @Frustrated-Programmer.

Did your require the plugging following the [Example of Use](https://github.com/bazzite/nativescript-vibrate#example-of-use) section?

**Comment by Frustrated-Programmer** [comment]
I did: 
``` 
    let vibrator = new require("nativescript-vibrate").Vibrate();
    console.dir(vibrator);
```
and got:
```
 ==== object dump start ====
JS: Vibrate()
JS: _observers: {}
JS: service: android.os.SystemVibrator@391c1cb
JS: ==== object dump end ====
```

**Comment by juliomrqz** [comment]
You're requiring the plugin this way:

```js
require("nativescript-vibrate").Vibrate();
```

but you must do this (without the _round brackets_ :nerd_face: ):

```js
require("nativescript-vibrate").Vibrate;
```

**Comment by Frustrated-Programmer** [comment]
I tried splitting it like you have in the docs. Not sure why it produces different results.
```
    let mod = require("nativescript-vibrate");
    let vibrator = new mod.Vibrate();
    console.dir(vibrator); 
```
But it now works. Tho why does the require() need to be assigned to a variable first?
