### ISSUE TITLE
"app is not defined" error

### ISSUE THREAD

**Issue by Burgov** [bazzite/nativescript-vibrate#8]
When I try to run this plugin on android, I get the error "app is not defined" from line 7 in https://github.com/bazzite/nativescript-vibrate/blame/develop/src/vibrate.android.ts

Am I missing something?

**Comment by Burgov** [comment]
Fixed it by doing platform remove android and platform add android as per documentation, but the issue, https://github.com/NativeScript/nativescript-cli/issues/669, that's referred to has long been fixed.

Additionally, the docs say the permission is automatically added, but it isn't

**Comment by juliomrqz** [comment]
@Burgov Those issues were fixed in the version 2.0.1.
